### ISSUE TITLE
Function "open-database" is difficult to use within REPL

### ISSUE THREAD

**Issue by dbushenko** [dscarpetti/codax#13]
I have following code:

    (defn init-db [ _db_ ]
      (c/assoc-at! _db_ [:counters :user-id] 1))
    
    (def DB (atom nil))
    
    (defn prepare-all [tests]
      (if-not @DB
        (reset! DB (c/open-database "db.test")))
      (init-db @DB))
    
    (use-fixtures :once prepare-all)

As you see this code prepares database connection for tests. In my normal workflow I recompile this class multiple times and try running tests each time. All goes well but after recompiling the variable DB is redefined and opened connection is lost somewhere.

Your function has all of them stored:

    (defn open-database [path & [backup-fn]]
      (let [path (to-canonical-path-string path)]
        (when (@open-databases path)
          (throw (ex-info "Database Already Open" {:cause :database-open
                                                   :message "The database at this path is already open."
                                                   :path path})))

So while I've lost the connection in my REPL it still physically exists somewhere and I cannot re-open the database again. I don't know how to fix this, maybe you can provide a function like "current-connection" accepting the database name so that I can obtain the existing connection and continue working without re-opening the DB?
Thanks!

**Comment by dbushenko** [comment]
I think I should have used defonce.

**Comment by dbushenko** [comment]
No, the error still shows up.

error: clojure.lang.ExceptionInfo: Database Already Open {:cause :database-open, :message "The database at this path is already open.", :path "D:\\Work\\users-manager\\db.test"}

**Comment by dscarpetti** [comment]
Thanks for the PR, though I wonder if there a simple way to solve the problem with the existing interface?

Would the following work in your use case:

```clojure
(defn get-database-connection [path]
  (c/close-database path)
  (c/open-database path))

;...
(defn prepare-all [tests]
  (reset! DB (get-database-connection "db.test"))
  (init-db))
```

**Comment by dbushenko** [comment]
Technically it works in my particular case, thanks. But do you really think that this wrapper is _logically_ correct? Instead of returning an already opened connection it closes and opens the DB again. What will be in concurrent threads?

    (defn close-database [path-or-db]
      (let [path (to-canonical-path-string
                  (if (string? path-or-db)
                    path-or-db
                    (:path path-or-db)))]
        (when-let [open-db (@open-databases path)]
          (locking (:write-lock open-db)

Lets say 2 threads are trying to close DB. Both check that open-db has something. One body acquires the lock, the second -- waits. The first closes the DB, and then the same does the second.

And what about open-database? Are there any means of threads synchronization?

**Comment by dscarpetti** [comment]
You're right. There are also some potential race conditions, particularly with respect to opening databases. If I recall, that is why I made opening a database multiple times throw an error, to dissuade usages that would attempt to open a database multiple times/across threads. The assumption was that a given database would be opened once during application initialization. After further consideration, that was/is a design flaw that should be corrected.

I threw together a potential solution in the [thread-safe-connections](https://github.com/dscarpetti/codax/compare/master...thread-safe-connections) branch. Basically, it defines `connection-lock` object and then locks it for opening/closing/destroying databases. This then allows `open-database` itself to be safely idempotent. An error is thrown if the backup-fn is changed, but otherwise calling `open-database` on an already opened database will simple return the existing db.

If you have a chance to take a look at it. I'd appreciate your opinion.

**Comment by dbushenko** [comment]
I've looked through the code. Having one monitor for all operations is a little brute-force, but for codax model it is OK, I think. And thanks for adjusting the function open-database, now it will fit my needs.

If I could criticize your code a little then I'd say that the function open-database does too much. It does 3 things instead of one:
1) it checks that the connection is already established and checks whether the backup function is correct.
2) it returns established connection
3) it opens the database (which is in fact -- main flow, and this flow is pretty large).

Also there are too many nested constructions.

I'd split it a bit so that all those logical things would be done by each separate function and 'open-database' would be like an orchestration of them. It could be like this:

    (defn open-database [ path & [backup-fn] ]
      (locking connection-lock
        (let [conn (existing-connection path backup-fn)]
          (or conn (open-new-connection path backup-fn)))))

I don't insist on this but I think that source code clarity matters.

**Comment by dscarpetti** [comment]
Yeah, a finer grained solution might ultimately be warranted. I can imagine a use case in which one is opening and closing many databases consistently (e.g. one per user) where it might create a critical bottleneck. In the meantime, it will at least be safe.

Good point on the separation of concerns in `open-database`. I've refactored per your suggestion.

**Comment by dscarpetti** [comment]
update has been deployed in 1.1.0-SNAPSHOT
