### ISSUE TITLE
Add examples of nippy

### ISSUE THREAD

**Issue by abhi18av** [dscarpetti/codax#18]
Hi @dscarpetti  

First off, thanks for this wonderful library! 

My request is that could you please add some `nippy` exames in the ReadMe ? I'm a beginner in clojure so I'd love to see a couple examples of non-map data being stored via nippy.

**Comment by dscarpetti** [comment]
Glad you like it!

Out of the box nippy will encode most (all?) of the standard clojure datatypes. So, basically, unless you are defining your own custom types, you shouldn't have any issue.

For example the following works fine right out of the box.

```clojure
(assoc-in! some-db [:my-vector] [1 2 3])

(get-in! some-db [:my-vector]); [1 2 3]
```

Does this address your question? 

I can see how the current ReadMe could be ambiguous on this point, I will update it to clarify.

**Comment by abhi18av** [comment]
Yes, it does help me understand better when you pointed this out here. But i feel, it wasn't too obvious before.

Please feel free to close this "issue" :)

**Comment by dscarpetti** [comment]
Thanks for bringing it to my attention. I updated the docs, so hopefully it will be easier for others to understand in the future.
