### ISSUE TITLE
Distribute non-AOT uberjar

### ISSUE THREAD

**Issue by mjmeintjes** [dscarpetti/codax#25]
AOT compiling means that this library's dependencies override any other dependencies (https://clojureverse.org/t/deploying-aot-compiled-libraries/2545/6?u=mjmeintjes).

This leads to very hard to debug errors when consumers use a newer version of the clojure.core.cache library.

**Comment by dscarpetti** [comment]
Thanks for info. Originally, it was intended to allow users to run codax as a standalone application to facilitate interacting with databases outside of a larger project. In practice, I suspect this almost never happens (at least, I never do it), so the impact should be minimal.
