### ISSUE TITLE
Support for java.time Instants

### ISSUE THREAD

**Issue by sooheon** [dscarpetti/codax#4]
The author of joda time has contributed java.time, and considers it an [improved](https://github.com/dm3/clojure.java-time#whats-different-in-java-time-api) effort. Modern clojure [libs](https://github.com/juxt/tick) are also preferring java.time. 

What are the steps we can take to add support for this type as keys in the db map?

**Comment by dscarpetti** [comment]
Adding a type requires 4 things:

1. a unique (but arbitrary) ordering tag which identifies the type and determines where it fits in the total ordering of the underlying b+ tree. 
2. a predicate fn to determine if the value is of that type
3. an encoding function which turns values of that type into strings whose lexicographical order matched their logical order (in this case ensuring that preceding dates sort before subsequent dates)
4. a decoding function which takes the string representation (actually a sequence of characters which must be `str/join`ed, for arcane reasons) and instantiates an object of the appropriate type.

The current joda-time implementation of these four elements is [here](https://github.com/dscarpetti/codax/blob/46fbf34cb26be6b0d83efc59a1baad5b8115b08f/src/codax/pathwise.clj#L68-L77) and [here](https://github.com/dscarpetti/codax/blob/46fbf34cb26be6b0d83efc59a1baad5b8115b08f/src/codax/pathwise.clj#L125-L128)

That's pretty much all there is to it. 

Briefly looking at the java.time docs, it seems that if the encoder & decoder pair allow optional appended timezone/offset information offset times, zone  times and instants can all be sorted together. Local date times would probably be separate, requiring their own ordering tag.

**Comment by dscarpetti** [comment]
Type explanation above has been added as doc/types.md for future reference.
